--1. 
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

--2.
SELECT STUDENT_NAME , STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME AS 학생이름, STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%' AND
STUDENT_ADDRESS LIKE '%경기도%' OR STUDENT_ADDRESS LIKE '%강원도%'
ORDER BY STUDENT_NAME ASC;

--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN ASC;

--5. ORDER BY절 뒤에 내림차순 혹은 오름차순을 한번 더 적을 수 있다.
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = 200402 AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;

--6. 
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

--7. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY CLASS_NAME ASC;

--8. GROUP BY 문을 사용할때 SELECT 절에서 찾고 싶은 컬럼명들은 전부 GROUP BY문에 표시해야한다.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
GROUP BY CLASS_NAME, PROFESSOR_NAME
ORDER BY PROFESSOR_NAME ASC;

--9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
GROUP BY CLASS_NAME, PROFESSOR_NAME;

SELECT * FROM TB_GRADE;

--10. 음악학과 학생들의 평점을 구하려고 한다. 음악학과 학생들의 학번, 학생이름, 전체평점을
-- 출력하는 문장 작성/ 평점은 소수점 1자리까지만 반올림해서 출력
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO, STUDENT_NAME;
-- ;

--11. 
SELECT DEPARTMENT_NAME AS 학과이름, STUDENT_NAME AS 학생이름, PROFESSOR_NAME AS 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';

--12.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = 015 AND TERM_NO LIKE '2007%';

-- 13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_STUDENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND COACH_PROFESSOR_NO IS NULL;

-- 14.
SELECT STUDENT_NAME, NVL(PROFESSOR_NAME,'지도교수미지정') AS 지도교수
FROM TB_STUDENT
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
WHERE NVL(COACH_PROFESSOR_NO,'지도교수미지정') = '지도교수미지정';

--15. ??
SELECT STUDENT_NO as 학번, STUDENT_NAME as 이름, DEPARTMENT_NAME as 학과이름, AVG(POINT)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING AVG(POINT) >= 4.0;
-- HAVING ABSENCE_YN = 'N' AND AVG(POINT) >= 4.0; - 이거는 왜 안될까
-- HAVING 절 뒤에 왜 그냥 POINT 만 넣으면 에러가 뜨는지

-- 16. 
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17. 
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '최경희');
                        
-- 18. 여기부터 다시하기
SELECT DISTINCT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = 001
AND POINT = (SELECT MAX(POINT)
                FROM TB_GRADE
                WHERE DEPARTMENT_NO = 001);