--1.
CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3.
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

--4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5.
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR(10);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR(20);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR(20);

--6.
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;

--7.
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN CLASS_TYPE_NAME TO PK_CLASS_TYPE_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;

--8.
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;

--9.
ALTER TABLE TB_DEPARTMENT 
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
FOREIGN KEY(CATEGORY) 
REFERENCES TB_CATEGORY(PK_CATEGORY_NAME);

--10.
CREATE VIEW VW_학생일반정보 AS
    (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT);
    
--11.
CREATE VIEW VW_지도면담 AS
    (SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
    );
DROP VIEW VW_지도면담;
    
SELECT * FROM VW_지도면담;   

--12.
CREATE VIEW VW_학과별학생수 AS
(SELECT DEPARTMENT_NAME AS 학과, COUNT(STUDENT_NAME) AS 학생수
    FROM TB_DEPARTMENT
    JOIN TB_STUDENT USING(DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME
);

CREATE OR REPLACE VIEW VW_학과별학생수 AS
SELECT DEPARTMENT_NAME AS 학과, 
       COUNT(STUDENT_NAME) AS 학생수,
       STUDENT_NO,
       STUDENT_NAME
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME, STUDENT_NO, STUDENT_NAME;


SELECT * FROM VW_학과별학생수;

--13.
UPDATE TB_STUDENT
SET STUDENT_NAME = '황동준'
WHERE STUDENT_NO = 'A213046';


-- 14.
CREATE TRIGGER TRG_VW
INSTEAD OF UPDATE OR INSERT OR DELETE ON VW_학과별학생수
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, '뷰에서 데이터 변경이 불가능합니다.');
END;

--15. (?)